ee350_csme_precision:
  hostname_contains: ee350-csme-precision
  compile_models: true
  dataset_paths:
    mnist: null
    cifar10: null
    imagenet: /mnt/hdd/datasets/imagenet
    redpajama: null
    redpajama_sample: null
gautschi-cluster:
  hostname_contains: gautschi.rcac.purdue.edu
  compile_models: true
  dataset_paths:
    mnist: null
    cifar10: null
    imagenet: /scratch/gautschi/jgammell/imagenet
    redpajama: /scratch/gautschi/jgammell/redpajama
    redpajama_sample: /scratch/gautschi/jgammell/redpajama_sample